name: Frontend Build and Deploy

on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    outputs:
      docker-tag: ${{ steps.vars.outputs.tag }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: './frontend/yarn.lock'
        
    - name: Install dependencies
      run: yarn install

    - name: Build frontend
      run: yarn build
      env:
        VITE_CLERK_PUBLISHABLE_KEY: pk_test_cGxlYXNpbmctc3R1cmdlb24tMTEuY2xlcmsuYWNjb3VudHMuZGV2JA
        VITE_BACKEND1_BASE_URL: http://localhost:3000/
        VITE_BACKEND2_BASE_URL: http://localhost:3000/
      
    - name: Upload Build to Github Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: frontend/dist
  
  trivy_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download frontend Docker artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-artifact
        path: ./artifacts

    - name: Load Docker image from artifact
      run: |
        docker load -i ./artifacts/frontend-artifact.tar
        docker images  # for debug

    - name: Run Trivy scan with HTML output
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/blog-frontend:${{ needs.build.outputs.docker-tag }}
        format: 'template'
        template: '@/contrib/html.tpl'
        output: 'trivy-report/report.html'

    - name: Upload Trivy report artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: trivy-report
        name: trivy-report
  

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url  }}
    runs-on: ubuntu-latest
    needs: [ build, trivy_scan ]
    steps:
    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: combined-site

    - name: Download Trivy scan report
      uses: actions/download-artifact@v4
      with:
        name: trivy-report
        path: combined-site/scan

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 
      with:
        path: combined-site

