name: Frontend Build and Deploy

on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: |
        cd frontend
        yarn install

    - name: Build frontend
      run: |
        cd frontend
        yarn build
      env:
        VITE_CLERK_PUBLISHABLE_KEY: pk_test_cGxlYXNpbmctc3R1cmdlb24tMTEuY2xlcmsuYWNjb3VudHMuZGV2JA
        VITE_BACKEND1_BASE_URL: http://localhost:3000/
        VITE_BACKEND2_BASE_URL: http://localhost:3000/

    - name: Upload Build to Github Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url  }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
