
name: Docker Image CI

on:
  push:
    branches: 
      - "dev"
  pull_request:
    branches: [ "dev" ]

jobs:

  pull_request_checks:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v4

    - name: Check if required files exist
      run: |
        test -f ./frontend/package.json && echo "Frontend package.json exists"
        test -f ./frontend/Dockerfile && echo "Frontend Dockerfile exists"

    - name: Check conventional commit messages
      uses: amannn/action-semantic-pull-request@v5
      with:
          githubBaseUrl: https://api.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'PRODUCTION' || 'DEVELOPMENT' }}
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Set Tag for Docker Image
      id: vars
      run : |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          VERSION=$(cat VERSION)
          echo "tag=$VERSION" >> $GITHUB_OUTPUT
        else
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||' | tr '/' '-')
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_OUTPUT
        fi
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
          
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v6
      with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ steps.vars.outputs.tag }}
          
    - name: Build and Push Backend1 Image
      uses: docker/build-push-action@v6
      with:
          context: ./backend1
          file: ./backend1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend1:${{ steps.vars.outputs.tag }}

    - name: Build and Push Backend2 Image
      uses: docker/build-push-action@v6
      with:
          context: ./backend2
          file: ./backend2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend2:${{ steps.vars.outputs.tag }}
