name: Release
on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Trigger Docker Build with Version
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: main.yml
          inputs: |
            version: ${GITHUB_REF#refs/tags/}
          token: ${{ secrets.GITHUB_TOKEN }}